apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: node-exporter
  annotations:
      prometheus.io/scrape: 'true'
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/component: node-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9100'
    spec:
      serviceAccountName: node-exporter
      containers:
      - name: node-exporter
        image: harbor.gnavi.co.jp/dockerhub_proxy/prom/node-exporter:v1.4.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2000m
            memory: 256Mi
          requests:
            cpu: 100m
        ports:
        - name: http
          containerPort: 9100
      hostNetwork: true
      hostPID: true

