apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: prometheus
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/scheme: 'http'
      prometheus.io/port: 'http'
spec:
  selector: 
    app.kubernetes.io/component: prometheus-server
  type: ClusterIP 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
